sudo: required
dist: trusty

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=pypy
  - TOX_ENV=docs
  - TOX_ENV=flake8

before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y libev-dev"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"
